# Generated by Django 3.2.1 on 2021-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='購入者Eメール', max_length=100)),
                ('price', models.IntegerField()),
                ('stripe_id', models.CharField(max_length=1000)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orderhistory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='値段')),
                ('detail', models.TextField(default='商品詳細', verbose_name='詳細')),
                ('image', models.ImageField(upload_to='image/', verbose_name='写真')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
