# Generated by Django 3.2.1 on 2021-05-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.CharField(default='商品名', max_length=100),
        ),
    ]
