# Generated by Django 3.1.7 on 2021-04-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produce',
            new_name='Product',
        ),
    ]
